ul_period = 15
lora_period = 300
pw_stat_period = 0
periodic_pos_period = 900
unknown = 0
geoloc_sensor = 10
geoloc_method = 6
antenna = 0
motion_nb_pos = 20
gps_timeout = 300
agps_timeout = 45
gps_ehpe = 5
gps_convergence = 70
config_flags = 18301499   # bit 20 set to 1
#config_flags = 17252923  # bit 20 set to 0
transmit_strat = 5
ble_beacon_cnt = 4
ble_beacon_timeout = 2
gps_standby_timeout = 0
confirmed_ul_bitmap = 0
confirmed_ul_retry = 3
motion_sensitivity = 131073
shock_detection = 126
periodic_activity_period = 0
motion_duration = 60
geofencing_scan_period = 0
geofencing_collect_period = 0
ble_rssi_filter = -80
temperature_high = 255
temperature_low = 255
temperature_action = 0
transmit_strat_custom = 12289
network_timeout_check = 432000
network_timeout_reset = 172800
collection_scan_type = 0
collection_nb_entry = 20
collection_ble_filter_type = 0
collection_ble_filter_main_1 = 0
collection_ble_filter_main_2 = 0
collection_ble_filter_sec_val = 0
collection_ble_filter_sec_mas = 0
battery_capacity = -1
reed_switch_configuration = 0
gnss_constellation = 2
prox_scan_pwr_min = -90
prox_distance_coef = 200
prox_scan_frequency = 1800
prox_backtrace_max_age = 256
prox_distance_sliding_window = 30
prox_exposure_50 = 200
prox_exposure_100 = 50
prox_exposure_150 = 22
prox_exposure_200 = 13
prox_exposure_250 = 0
prox_exposure_300 = 0
prox_exposure_400 = 0
prox_alarm_dist_immediate = 1
prox_alarm_exposure = 12000
prox_warn_dist_immediate = 10
prox_warn_exposure = 6000
prox_record_dist_immediate = 20
prox_record_exposure = 3700
prox_alarm_buz_duration = 5
prox_warn_buz_duration = 5
prox_contact_policy = 0
prox_scan_duration = 10
prox_scan_window = 120
prox_scan_interval = 125
prox_alarm_remanence = 30
prox_warn_remanence = 30
prox_bcn_repeat = 100
prox_bcn_tx_power = -41
prox_reminder_period = 20
prox_reminder_distance = 20
prox_warn_disable_dist = 25
prox_alarm_disable_dist = 25
prox_max_speed_filter = 15
prox_max_update = 3600
position_ble_filter_type = 4
position_ble_filter_main_1 = -1410465791
position_ble_filter_main_2 = -1410465790
position_ble_filter_sec_value = 0
position_ble_filter_sec_mask = 0
position_ble_report_type = 1
buzzer_volume = 5
angle_detect_mode = 0
angle_ref_acq = 2
angle_ref_acc_x = 0
angle_ref_acc_y = 0
angle_ref_acc_z = 0
angle_critical = 30
angle_critical_hyst = 5
angle_report_mode = 1
angle_report_period = 300
angle_report_repeat = 0
angle_rising_time = 5
angle_falling_time = 5
angle_learning_time = 5
angle_acc_accuracy = 100
angle_deviation_delta = 0
angle_deviation_min_interval = 10
angle_deviation_max_interval = 0
default_profile = 0
password = 123
gps_t0_timeout = 40
gps_fix_timeout = 260
geofencing_scan_duration = 370
beaconing_type = 0
beaconing_tx_power = 2
beaconing_static_interval = 10000
beaconing_motion_interval = 333
beaconing_motion_duration = 20
ble_cnx_adv_duration = 600
beacon_id_0 = 0
beacon_id_1 = 0
beacon_id_2 = 0
beacon_id_3 = 0
beacon_id_4 = 0
sos_period = 15
motion_debounce = 1
button_mapping = 74768
default_datarate = -1
gps_ehpe_motion = 5
gps_convergence_motion = 15
gps_t0_timeout_motion = 40
mode = 1
